### ISSUE TITLE
User can add a trip

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/RambleReady#1]
![image](https://user-images.githubusercontent.com/73143959/113634189-30b32280-9623-11eb-9c01-f74c1e5c557b.png)
![image](https://user-images.githubusercontent.com/73143959/113634228-445e8900-9623-11eb-9586-8813a21a4b6f.png)

**Task List:**

- [x] Set up react project
- [x] Add header
- [x] Add navbar component
- [x] Add trip page component
- [x] Add trip card component
- [x] Add trips page styling
- [x] Add new trip form component
- [x] Add form styling
- [x] Add handler to close button
- [x] Add new trip to database
- [x] Correct all bugs & styling
