### ISSUE TITLE
User can see trip expenses pie chart

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/RambleReady#11]
![image](https://user-images.githubusercontent.com/73143959/113635006-b1265300-9624-11eb-8b71-df2fba672dfc.png)

**Task List:**

- [x] Install Chart.js
- [x] Import Chart to stats page
- [x] Add div and canvas for chart
- [x] Add chart data
