### ISSUE TITLE
User can see daily expenses bar graph

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/RambleReady#12]
![image](https://user-images.githubusercontent.com/73143959/113635031-bb485180-9624-11eb-9185-9489ec2373c6.png)

**Task List:** 

- [x] Create bar chart component
- [x] Import bar chart component to stats page
- [x] Create function to get total expenses by day data
- [x] Pass data to bar chart component via props
- [x] Add styling to bar chart and stats page
