### ISSUE TITLE
User can see a list of trips

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/RambleReady#14]
![image](https://user-images.githubusercontent.com/73143959/113915600-d1c0eb00-9793-11eb-875b-536017cf21f6.png)

**Task List:**

- [x] Add http get request for all trips
- [x] Create react accordion component
- [x] Add styling for accordion component
