### ISSUE TITLE
User can edit a trip

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/RambleReady#2]
![image](https://user-images.githubusercontent.com/73143959/113634368-78d24500-9623-11eb-948b-1434b7107606.png)

**Task List:**

- [x] Add http request
- [x] Add edit form
- [x] Populate edit form
- [x] Add styling to form
