### ISSUE TITLE
User can delete a trip

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/RambleReady#3]
![image](https://user-images.githubusercontent.com/73143959/113634430-97d0d700-9623-11eb-96fd-1124f62809d2.png)
![image](https://user-images.githubusercontent.com/73143959/113634465-a4552f80-9623-11eb-883d-2b29e3e9e93e.png)

**Task List:** 

- [x] Add delete http request by tripId to index.js
- [x] Add state to hold if user is deleting or editing
- [x] Add handle to delete button to render confirm delete
- [x] Add handle to close button to render edit form
- [x] Add handle to confirm button to delete trip
- [x] Add confirm delete render elements
- [x] Add styling to confirm delete elements
