### ISSUE TITLE
User can use a currency converter

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/RambleReady#4]
![image](https://user-images.githubusercontent.com/73143959/113634557-cb136600-9623-11eb-8184-30e230142c87.png)

**Task List:**

- [x] Add API key to .env
- [x] Create new expense page
- [x] Add new expense page to app
- [x] Add date, currency, rate to state
- [x] Add calculator elements
- [x] Add fetch request to API
- [x] Add page styling
