### ISSUE TITLE
User can add an expense

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/RambleReady#5]
![image](https://user-images.githubusercontent.com/73143959/113634605-dcf50900-9623-11eb-9970-569b50f133da.png)
![image](https://user-images.githubusercontent.com/73143959/113634634-eb432500-9623-11eb-9a67-fe39d4983198.png)

**Task List:**

- [x] Add expenses table with columns: tripId, expenseId, date, category, subcategory, notes, currency, exchangeRate, amountUSD
- [x] Add http post request to expenses table to index.js
- [x] Create new expense detail form component with inputs for amount, date, notes, and the following category/subcategory options:
- [x] Food & Drink: Breakfast, Lunch, Dinner, Coffee, Drinks, Other
- [x] Local Transportation: Car Rental, Fuel, Taxi, Train, Public, Other
- [x] Shopping: Souvenirs, Gifts, Supplies, Other
- [x] Entertainment: Attractions, Tours, Excursions, Events, Other
- [x] Lodging: Vacation Rental, Hotel, Hostel, Campsite, Other
- [x] International Transport: Airfare, Train, Bus, Other
- [x] Administrative: Travel Insurance, Passports, Visas, Pet Boarding, Other
- [x] Medical: Immunizations, Prescriptions, Medical Insurance, Pharmacy, Medical Care, Other
- [x] Miscellaneous (no subcategories) 
- [x] Add variable object to new expense page for categories/subcategories
- [x] Add event handler to icons to render corresponding category detail form
- [x] Add styling to new expense detail form
- [x] Add toggle switch for USD and current currency
- [x] Add handler to return to add expense main page on cancel
- [x] Add function to calculate USD total using exchangeRate
- [x] Add handler to calculate and render conversion result
- [x] Add countries table
- [x] Add http get request for all countries
- [x] Add countries as drop down option on add trip form
- [x] Disable country select on edit trip form
- [x] Disable icon buttons on new expense main page unless trip is chosen
- [x] Add fetch request on trip select to set tripId and currency in state
- [x] Render currency in calculator placeholder
- [x] Render currency as toggle option on detail page
- [x] Amount entered in USD submit with no conversion
- [x] Amount entered in foreign currency calculate conversion on submit
- [x] Add any additional styling and fix all bugs
