### ISSUE TITLE
User can see current trip balance

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/RambleReady#6]
![image](https://user-images.githubusercontent.com/73143959/113634748-2a717600-9624-11eb-9482-db31d970b869.png)

**Task List:**

- [x] Add http request for all expenses by tripId
- [x] Add homepage
- [x] Add trip select drop down
- [x] Add fetch request for expenses for trip selected
- [x] Add method to sum expenses and render balance based on trip budget
- [x] Add progress bar to show amount spent
- [x] Add component styling
- [x] Add navbar routing
