### ISSUE TITLE
User can see current daily balance

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/RambleReady#7]
![image](https://user-images.githubusercontent.com/73143959/113634775-39582880-9624-11eb-9c2e-c45149682a84.png)

**Task List:**

- [x] Add expenses to http get request
- [x] Add today's date to homepage state
- [x] Render daily total
- [x] Style daily total component
