### ISSUE TITLE
User can see daily budget

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/RambleReady#8]
![image](https://user-images.githubusercontent.com/73143959/113634800-4543ea80-9624-11eb-9867-c35efa9ae186.png)

**Task List:**

- [x] Add trip length function
- [x] Add function to calculate daily budget based on trip length and trip budget
- [x] Render daily budget to home page
- [x] Style daily budget component
