### ISSUE TITLE
User can see daily expense line items

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/RambleReady#9]
![image](https://user-images.githubusercontent.com/73143959/113634850-60aef580-9624-11eb-86e6-d2b73ca36765.png)
![image](https://user-images.githubusercontent.com/73143959/114944289-28659f00-9dfc-11eb-8cf9-f7be2d91c924.png)

**Task List:**

- [x] Add http get request for all trip expenses
- [x] Add stats page
- [x] Add trip select drop down to page
- [x] Add fetch request for expenses by tripId
- [x] Add daily expenses accordion
- [x] Add styling to page
